# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ocr_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ocr_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ocr_service.proto\x12\x03ocr\"M\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x14\n\x0cimage_format\x18\x02 \x01(\t\x12\x13\n\x0b\x61uto_rotate\x18\x03 \x01(\x08\"Z\n\x0bOCRResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12#\n\x0btext_blocks\x18\x03 \x03(\x0b\x32\x0e.ocr.TextBlock\"6\n\x11\x42\x61tchImageRequest\x12!\n\x06images\x18\x01 \x03(\x0b\x32\x11.ocr.ImageRequest\"]\n\x10\x42\x61tchOCRResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12!\n\x07results\x18\x03 \x03(\x0b\x32\x10.ocr.BatchResult\"Z\n\x0b\x42\x61tchResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12#\n\x0btext_blocks\x18\x03 \x03(\x0b\x32\x0e.ocr.TextBlock\"L\n\tTextBlock\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x1d\n\x03\x62ox\x18\x03 \x01(\x0b\x32\x10.ocr.BoundingBox\"m\n\x0b\x42oundingBox\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\x12\n\n\x02x3\x18\x05 \x01(\x02\x12\n\n\x02y3\x18\x06 \x01(\x02\x12\n\n\x02x4\x18\x07 \x01(\x02\x12\n\n\x02y4\x18\x08 \x01(\x02\x32\x8a\x01\n\nOCRService\x12\x35\n\x0cProcessImage\x12\x11.ocr.ImageRequest\x1a\x10.ocr.OCRResponse\"\x00\x12\x45\n\x12ProcessBatchImages\x12\x16.ocr.BatchImageRequest\x1a\x15.ocr.BatchOCRResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocr_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=26
  _globals['_IMAGEREQUEST']._serialized_end=103
  _globals['_OCRRESPONSE']._serialized_start=105
  _globals['_OCRRESPONSE']._serialized_end=195
  _globals['_BATCHIMAGEREQUEST']._serialized_start=197
  _globals['_BATCHIMAGEREQUEST']._serialized_end=251
  _globals['_BATCHOCRRESPONSE']._serialized_start=253
  _globals['_BATCHOCRRESPONSE']._serialized_end=346
  _globals['_BATCHRESULT']._serialized_start=348
  _globals['_BATCHRESULT']._serialized_end=438
  _globals['_TEXTBLOCK']._serialized_start=440
  _globals['_TEXTBLOCK']._serialized_end=516
  _globals['_BOUNDINGBOX']._serialized_start=518
  _globals['_BOUNDINGBOX']._serialized_end=627
  _globals['_OCRSERVICE']._serialized_start=630
  _globals['_OCRSERVICE']._serialized_end=768
# @@protoc_insertion_point(module_scope)
