// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.2
// source: ocr/proto/ocr_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImageData      []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	ImageFormat    string                 `protobuf:"bytes,2,opt,name=image_format,json=imageFormat,proto3" json:"image_format,omitempty"` // 可以是"jpg", "png"等
	AutoRotate     bool                   `protobuf:"varint,3,opt,name=auto_rotate,json=autoRotate,proto3" json:"auto_rotate,omitempty"`
	PreprocessType string                 `protobuf:"bytes,4,opt,name=preprocess_type,json=preprocessType,proto3" json:"preprocess_type,omitempty"` // 可以是"auto", "basic", "text", "document", "none"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImageRequest) Reset() {
	*x = ImageRequest{}
	mi := &file_ocr_proto_ocr_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRequest) ProtoMessage() {}

func (x *ImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_proto_ocr_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRequest.ProtoReflect.Descriptor instead.
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return file_ocr_proto_ocr_service_proto_rawDescGZIP(), []int{0}
}

func (x *ImageRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ImageRequest) GetImageFormat() string {
	if x != nil {
		return x.ImageFormat
	}
	return ""
}

func (x *ImageRequest) GetAutoRotate() bool {
	if x != nil {
		return x.AutoRotate
	}
	return false
}

func (x *ImageRequest) GetPreprocessType() string {
	if x != nil {
		return x.PreprocessType
	}
	return ""
}

type OCRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TextBlocks    []*TextBlock           `protobuf:"bytes,3,rep,name=text_blocks,json=textBlocks,proto3" json:"text_blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCRResponse) Reset() {
	*x = OCRResponse{}
	mi := &file_ocr_proto_ocr_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCRResponse) ProtoMessage() {}

func (x *OCRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_proto_ocr_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCRResponse.ProtoReflect.Descriptor instead.
func (*OCRResponse) Descriptor() ([]byte, []int) {
	return file_ocr_proto_ocr_service_proto_rawDescGZIP(), []int{1}
}

func (x *OCRResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OCRResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *OCRResponse) GetTextBlocks() []*TextBlock {
	if x != nil {
		return x.TextBlocks
	}
	return nil
}

type BatchImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*ImageRequest        `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchImageRequest) Reset() {
	*x = BatchImageRequest{}
	mi := &file_ocr_proto_ocr_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchImageRequest) ProtoMessage() {}

func (x *BatchImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_proto_ocr_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchImageRequest.ProtoReflect.Descriptor instead.
func (*BatchImageRequest) Descriptor() ([]byte, []int) {
	return file_ocr_proto_ocr_service_proto_rawDescGZIP(), []int{2}
}

func (x *BatchImageRequest) GetImages() []*ImageRequest {
	if x != nil {
		return x.Images
	}
	return nil
}

type BatchOCRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Results       []*BatchResult         `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchOCRResponse) Reset() {
	*x = BatchOCRResponse{}
	mi := &file_ocr_proto_ocr_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchOCRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOCRResponse) ProtoMessage() {}

func (x *BatchOCRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_proto_ocr_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOCRResponse.ProtoReflect.Descriptor instead.
func (*BatchOCRResponse) Descriptor() ([]byte, []int) {
	return file_ocr_proto_ocr_service_proto_rawDescGZIP(), []int{3}
}

func (x *BatchOCRResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchOCRResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BatchOCRResponse) GetResults() []*BatchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type BatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TextBlocks    []*TextBlock           `protobuf:"bytes,3,rep,name=text_blocks,json=textBlocks,proto3" json:"text_blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResult) Reset() {
	*x = BatchResult{}
	mi := &file_ocr_proto_ocr_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResult) ProtoMessage() {}

func (x *BatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_proto_ocr_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResult.ProtoReflect.Descriptor instead.
func (*BatchResult) Descriptor() ([]byte, []int) {
	return file_ocr_proto_ocr_service_proto_rawDescGZIP(), []int{4}
}

func (x *BatchResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BatchResult) GetTextBlocks() []*TextBlock {
	if x != nil {
		return x.TextBlocks
	}
	return nil
}

type TextBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Box           *BoundingBox           `protobuf:"bytes,3,opt,name=box,proto3" json:"box,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextBlock) Reset() {
	*x = TextBlock{}
	mi := &file_ocr_proto_ocr_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextBlock) ProtoMessage() {}

func (x *TextBlock) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_proto_ocr_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextBlock.ProtoReflect.Descriptor instead.
func (*TextBlock) Descriptor() ([]byte, []int) {
	return file_ocr_proto_ocr_service_proto_rawDescGZIP(), []int{5}
}

func (x *TextBlock) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextBlock) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TextBlock) GetBox() *BoundingBox {
	if x != nil {
		return x.Box
	}
	return nil
}

type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X1            float32                `protobuf:"fixed32,1,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            float32                `protobuf:"fixed32,2,opt,name=y1,proto3" json:"y1,omitempty"`
	X2            float32                `protobuf:"fixed32,3,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2            float32                `protobuf:"fixed32,4,opt,name=y2,proto3" json:"y2,omitempty"`
	X3            float32                `protobuf:"fixed32,5,opt,name=x3,proto3" json:"x3,omitempty"`
	Y3            float32                `protobuf:"fixed32,6,opt,name=y3,proto3" json:"y3,omitempty"`
	X4            float32                `protobuf:"fixed32,7,opt,name=x4,proto3" json:"x4,omitempty"`
	Y4            float32                `protobuf:"fixed32,8,opt,name=y4,proto3" json:"y4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_ocr_proto_ocr_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_proto_ocr_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_ocr_proto_ocr_service_proto_rawDescGZIP(), []int{6}
}

func (x *BoundingBox) GetX1() float32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *BoundingBox) GetY1() float32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *BoundingBox) GetX2() float32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *BoundingBox) GetY2() float32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

func (x *BoundingBox) GetX3() float32 {
	if x != nil {
		return x.X3
	}
	return 0
}

func (x *BoundingBox) GetY3() float32 {
	if x != nil {
		return x.Y3
	}
	return 0
}

func (x *BoundingBox) GetX4() float32 {
	if x != nil {
		return x.X4
	}
	return 0
}

func (x *BoundingBox) GetY4() float32 {
	if x != nil {
		return x.Y4
	}
	return 0
}

var File_ocr_proto_ocr_service_proto protoreflect.FileDescriptor

var file_ocr_proto_ocr_service_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x6f, 0x63, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x63, 0x72, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6f,
	0x63, 0x72, 0x22, 0x9a, 0x01, 0x0a, 0x0c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x46,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x72, 0x6f,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x6f,
	0x52, 0x6f, 0x74, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x72, 0x65, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x70, 0x72, 0x65, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x7d, 0x0a, 0x0b, 0x4f, 0x43, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a,
	0x0b, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6f, 0x63, 0x72, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x52, 0x0a, 0x74, 0x65, 0x78, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x22, 0x3e,
	0x0a, 0x11, 0x42, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6f, 0x63, 0x72, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x22, 0x7d,
	0x0a, 0x10, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x43, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x2a, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x63, 0x72, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x7d, 0x0a,
	0x0b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x74,
	0x65, 0x78, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x6f, 0x63, 0x72, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x52, 0x0a, 0x74, 0x65, 0x78, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x22, 0x63, 0x0a, 0x09,
	0x54, 0x65, 0x78, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x22, 0x0a,
	0x03, 0x62, 0x6f, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x63, 0x72,
	0x2e, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x78, 0x52, 0x03, 0x62, 0x6f,
	0x78, 0x22, 0x8d, 0x01, 0x0a, 0x0b, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x6f,
	0x78, 0x12, 0x0e, 0x0a, 0x02, 0x78, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x78,
	0x31, 0x12, 0x0e, 0x0a, 0x02, 0x79, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x79,
	0x31, 0x12, 0x0e, 0x0a, 0x02, 0x78, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x78,
	0x32, 0x12, 0x0e, 0x0a, 0x02, 0x79, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x79,
	0x32, 0x12, 0x0e, 0x0a, 0x02, 0x78, 0x33, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x78,
	0x33, 0x12, 0x0e, 0x0a, 0x02, 0x79, 0x33, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x79,
	0x33, 0x12, 0x0e, 0x0a, 0x02, 0x78, 0x34, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x78,
	0x34, 0x12, 0x0e, 0x0a, 0x02, 0x79, 0x34, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x79,
	0x34, 0x32, 0x8a, 0x01, 0x0a, 0x0a, 0x4f, 0x43, 0x52, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x35, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x12, 0x11, 0x2e, 0x6f, 0x63, 0x72, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x6f, 0x63, 0x72, 0x2e, 0x4f, 0x43, 0x52, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x42, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x16, 0x2e,
	0x6f, 0x63, 0x72, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6f, 0x63, 0x72, 0x2e, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x4f, 0x43, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_ocr_proto_ocr_service_proto_rawDescOnce sync.Once
	file_ocr_proto_ocr_service_proto_rawDescData []byte
)

func file_ocr_proto_ocr_service_proto_rawDescGZIP() []byte {
	file_ocr_proto_ocr_service_proto_rawDescOnce.Do(func() {
		file_ocr_proto_ocr_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ocr_proto_ocr_service_proto_rawDesc), len(file_ocr_proto_ocr_service_proto_rawDesc)))
	})
	return file_ocr_proto_ocr_service_proto_rawDescData
}

var file_ocr_proto_ocr_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ocr_proto_ocr_service_proto_goTypes = []any{
	(*ImageRequest)(nil),      // 0: ocr.ImageRequest
	(*OCRResponse)(nil),       // 1: ocr.OCRResponse
	(*BatchImageRequest)(nil), // 2: ocr.BatchImageRequest
	(*BatchOCRResponse)(nil),  // 3: ocr.BatchOCRResponse
	(*BatchResult)(nil),       // 4: ocr.BatchResult
	(*TextBlock)(nil),         // 5: ocr.TextBlock
	(*BoundingBox)(nil),       // 6: ocr.BoundingBox
}
var file_ocr_proto_ocr_service_proto_depIdxs = []int32{
	5, // 0: ocr.OCRResponse.text_blocks:type_name -> ocr.TextBlock
	0, // 1: ocr.BatchImageRequest.images:type_name -> ocr.ImageRequest
	4, // 2: ocr.BatchOCRResponse.results:type_name -> ocr.BatchResult
	5, // 3: ocr.BatchResult.text_blocks:type_name -> ocr.TextBlock
	6, // 4: ocr.TextBlock.box:type_name -> ocr.BoundingBox
	0, // 5: ocr.OCRService.ProcessImage:input_type -> ocr.ImageRequest
	2, // 6: ocr.OCRService.ProcessBatchImages:input_type -> ocr.BatchImageRequest
	1, // 7: ocr.OCRService.ProcessImage:output_type -> ocr.OCRResponse
	3, // 8: ocr.OCRService.ProcessBatchImages:output_type -> ocr.BatchOCRResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ocr_proto_ocr_service_proto_init() }
func file_ocr_proto_ocr_service_proto_init() {
	if File_ocr_proto_ocr_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocr_proto_ocr_service_proto_rawDesc), len(file_ocr_proto_ocr_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ocr_proto_ocr_service_proto_goTypes,
		DependencyIndexes: file_ocr_proto_ocr_service_proto_depIdxs,
		MessageInfos:      file_ocr_proto_ocr_service_proto_msgTypes,
	}.Build()
	File_ocr_proto_ocr_service_proto = out.File
	file_ocr_proto_ocr_service_proto_goTypes = nil
	file_ocr_proto_ocr_service_proto_depIdxs = nil
}
